# .github/workflows/ci.yml
name: CI on Render.com

on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment:
      name: render.com
      url: https://tictactoe-flask-fdro.onrender.com
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        # Only run this step if the branch is master
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"