name: Okteto Preview Deployment

on: [pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: 
      name: preview   
      #url: https://tictactoe-flask-pr-${{ github.event.number }}-mauricio-sousa.cloud.okteto.net
    steps:
    - name: Set context to Okteto Cloud
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy your preview environment
      uses: okteto/deploy-preview@latest
