name: Production Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production    
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Set context to Okteto Cloud
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Build and deploy application container to Okteto Flask Namespace
      uses: okteto/deploy-stack@latest
      with:
        name: tictactoe-flask
        build: true      