name: Okteto TicTacToe Flask Game CI

on: [push]

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2    
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: okteto.dev/tictactoe-game:${{ github.sha }}

    - name: Deploy preview environment
          uses: okteto/deploy-preview@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            name: staging-${{ github.event.number }}-OKTETO_USERNAME
            scope: personal
            timeout: 15m        