name: Okteto TicTacToe Flask Game CI

on: [push]

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2    
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: okteto.dev/tictactoe-game:${{ github.sha }}