name: Okteto TicTacToe Flask Game CI

on: [push]

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2  

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: okteto.dev/tictactoe-game:latest   
        tag: okteto.dev/tictactoe-game:${{ github.sha }}     

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: mauricio-sousa

#    - name: Deploy preview environment
#      uses: okteto/deploy-preview@latest
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        name: staging-${{ github.event.number }}-mauricio-sousa
#        scope: personal
#        timeout: 15m        

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: staging-${{ github.event.number }}-mauricio-sousa
        timeout: 15m