on: [push]

name: TicTacToe Flask Game

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: okteto.dev/tictactoe-game:${{ github.sha }}