name: Okteto Preview Deployment

on: [pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: 
      name: preview   
      url: https://tictactoe-flask-dev-mauricio-sousa.cloud.okteto.net
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Set context to Okteto Cloud
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy your preview environment
      uses: okteto/deploy-preview@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: dev-mauricio-sousa
        scope: personal
        timeout: 15m