name: Okteto TicTacToe Flask Game CI

on: [push]

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2  

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: mauricio-sousa

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: staging-${{ github.event.number }}-mauricio-sousa
        timeout: 15m     